# Generated by Django 4.2.5 on 2023-10-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchapp', '0003_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='passw',
            new_name='password',
        ),
        migrations.AddField(
            model_name='sermon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sermons/'),
        ),
    ]
