# Generated by Django 4.2.5 on 2023-10-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchapp', '0004_rename_passw_login_password_sermon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
