# Generated by Django 4.2.5 on 2023-10-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchapp', '0005_alter_sermon_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='upload_img',
            new_name='uploads_img',
        ),
        migrations.RenameModel(
            old_name='upload_video',
            new_name='uploads_video',
        ),
        migrations.DeleteModel(
            name='Event_church',
        ),
        migrations.AlterField(
            model_name='sermon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
