# Generated by Django 4.2.5 on 2023-10-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchapp', '0006_rename_upload_img_uploads_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
