# Generated by Django 4.2.5 on 2023-10-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchapp', '0007_sermon_video_file_alter_sermon_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
            ],
        ),
    ]
