# Generated by Django 4.2.5 on 2023-10-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchapp', '0008_event_church'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event_church',
            new_name='Eventchurch',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='image',
        ),
        migrations.AddField(
            model_name='sermon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploads_img',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='uploads_video',
            name='clips',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
        migrations.DeleteModel(
            name='MemberPortal',
        ),
    ]
