# Generated by Django 4.2.5 on 2023-10-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churchapp', '0009_rename_event_church_eventchurch_delete_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sermon',
            old_name='description',
            new_name='message',
        ),
    ]
