# Generated by Django 4.2.5 on 2023-10-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchapp', '0010_rename_description_sermon_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recentposts/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='recentposts/')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
