# Generated by Django 4.2.5 on 2023-10-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churchapp', '0011_recentpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentpost',
            name='date',
        ),
    ]
