# Generated by Django 4.2.5 on 2023-10-08 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churchapp', '0012_remove_recentpost_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sermon',
            old_name='audio_file',
            new_name='audio',
        ),
        migrations.RenameField(
            model_name='sermon',
            old_name='video_file',
            new_name='video',
        ),
    ]
