# Generated by Django 4.2.5 on 2023-10-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchapp', '0014_media_delete_uploads_img_delete_uploads_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='clips',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
