# Generated by Django 4.2.5 on 2023-10-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchapp', '0015_alter_media_clips_alter_media_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='image',
        ),
        migrations.AddField(
            model_name='media',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='uploads/audio/'),
        ),
    ]
