# Generated by Django 4.2.5 on 2023-10-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churchapp', '0016_remove_media_image_media_audio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recentpost',
            old_name='video_file',
            new_name='video',
        ),
    ]
