# Generated by Django 4.2.5 on 2023-10-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchapp', '0017_rename_video_file_recentpost_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='clips',
        ),
        migrations.AddField(
            model_name='media',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/video'),
        ),
    ]
