# Generated by Django 4.2.5 on 2023-10-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchapp', '0018_remove_media_clips_media_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/video/'),
        ),
    ]
